spring.application.name=Application

db.url=jdbc:mysql://tramway.proxy.rlwy.net:57864/QuanLyNhaThuoc
db.username=root
db.password=RSfJaDbgzwfGdkHBtEGwLPhFyXVemcGZ
db.driver=com.mysql.cj.jdbc.Driver

server.port=8080
spring.web.resources.static-locations=file:src/main/java/com/quanlycuahangthuoc/resources/static/
