spring.application.name=Application

db.url=jdbc:mysql://quanlyphongkham-doanquanlyphongkham.e.aivencloud.com:20567/QuanLyNhaThuoc?sslMode=REQUIRED
db.username=avnadmin
db.password=AVNS_P0GmFQ6e6gYGhk0ooIV
db.driver=com.mysql.cj.jdbc.Driver

server.port=8080

spring.web.resources.static-locations=classpath:/com/quanlycuahangthuoc/resources/static/